### ISSUE TITLE
Sending the process-related message to JMS queue failed

### ISSUE THREAD

**Issue by victorhrsilva** [servicecatalog/development#604]
[Version]
16.1 fix6+ 2017/03/14

**[Error msg in server.log]**
[2017-03-15T12:51:02.028+0100] [glassfish 4.1] [INFO] [] [javax.resourceadapter.mqjmsra.xa] [tid: _ThreadID=26 _ThreadName=http-listener-1(1)] [timeMillis: 1489578662028] [levelValue: 800] [[
  DXAR:start():Warning: XAResource with state CREATED received diff Xid for open txnId:switching transactionId:
DXAR  Xid=(GlobalTransactionID=[B@60d11987, BranchQualifier=[B@68c6aebb) 
DXAR TXid=2346193788044085248
got   Xid=(GlobalTransactionID=[B@3735a365, BranchQualifier=[B@2db49be8) 
got  TXid=2346193788044086016]]

[2017-03-15T12:51:02.039+0100] [glassfish 4.1] [SEVERE] [] [javax.jms.Session.mqjmsra] [tid: _ThreadID=223 _ThreadName=__ejb-thread-pool6] [timeMillis: 1489578662039] [levelValue: 1000] [[
  MQJMSRA_DS4001: JMSServiceException on send message:sendMessage: Sending message failed. Connection ID: 2346193787890764800 Caused by:com.sun.messaging.jmq.jmsserver.util.BrokerException: [B4403]: Exception on processing produced message PacketReference[1934-192.168.99.1(b4:41:42:5d:4c:9d)-1-1489578662032][TID=2346193788044086016, null]: Unexpected Broker Exception: [Transaction 2346193788044086016[COMPLETE(4)]: is not in STARTED(1) state] ]]

[2017-03-15T12:51:02.042+0100] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=26 _ThreadName=Thread-8] [timeMillis: 1489578662042] [levelValue: 800] [[
  Retrieving document at 'http://g02plxnnow29239.g02.fujitsu.local:9280/example-service/services/ProvisioningService?wsdl'.]]

[2017-03-15T12:51:02.045+0100] [glassfish 4.1] [SEVERE] [] [javax.resourceadapter.mqjmsra.outbound.connection] [tid: _ThreadID=223 _ThreadName=__ejb-thread-pool6] [timeMillis: 1489578662045] [levelValue: 1000] [[
  rollbackTransaction (XA) on JMSService:jmsdirect failed for connectionId:2346193787890764800:transactionId=2346193788044086016 due to Unknown JMSService server error ERROR: com.sun.messaging.jmq.jmsserver.util.BrokerException: Transaction XID mismatch 473032504C584E4E4F5732393233392C7365727665722C50383033372C00DE290000C3E3AAD1473032504C584E4E4F5732393233392C7365727665722C5038303337, expected 473032504C584E4E4F5732393233392C7365727665722C50383033372C01DD290000C3E3AAD1473032504C584E4E4F5732393233392C7365727665722C5038303337 for transaction 2346193788044086016]]

[2017-03-15T12:51:02.045+0100] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=26 _ThreadName=Thread-8] [timeMillis: 1489578662045] [levelValue: 800] [[
  Retrieving schema at 'ProvisioningService?xsd=ProvisioningService_schema1.xsd', relative to 'http://g02plxnnow29239.g02.fujitsu.local:9280/example-service/services/ProvisioningService?wsdl'.]]

[2017-03-15T12:51:02.045+0100] [glassfish 4.1] [WARNING] [jts.unexpected_error_occurred_twopc_rollback] [javax.enterprise.system.core.transaction.com.sun.jts.jtsxa] [tid: _ThreadID=223 _ThreadName=__ejb-thread-pool6] [timeMillis: 1489578662045] [levelValue: 900] [[
  JTS5068: Unexpected error occurred in rollback
javax.transaction.xa.XAException
	at com.sun.messaging.jms.ra.DirectXAResource.rollback(DirectXAResource.java:738)
	at com.sun.messaging.jms.ra.DirectXAResource.rollback(DirectXAResource.java:689)
	at com.sun.jts.jta.TransactionState._rollback(TransactionState.java:202)
	at com.sun.jts.jta.TransactionState.rollback(TransactionState.java:180)
	at com.sun.jts.jtsxa.OTSResourceImpl.rollback(OTSResourceImpl.java:333)
	at com.sun.jts.CosTransactions.RegisteredResources.distributeRollback(RegisteredResources.java:1040)
	at com.sun.jts.CosTransactions.TopCoordinator.rollback(TopCoordinator.java:2291)
	at com.sun.jts.CosTransactions.CoordinatorTerm.rollback(CoordinatorTerm.java:530)
	at com.sun.jts.CosTransactions.TerminatorImpl.rollback(TerminatorImpl.java:286)
	at com.sun.jts.CosTransactions.CurrentImpl.rollback(CurrentImpl.java:767)
	at com.sun.jts.jta.TransactionManagerImpl.rollback(TransactionManagerImpl.java:372)
	at com.sun.enterprise.transaction.jts.JavaEETransactionManagerJTSDelegate.rollbackDistributedTransaction(JavaEETransactionManagerJTSDelegate.java:219)
	at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.rollback(JavaEETransactionManagerSimplified.java:892)
	at com.sun.ejb.containers.EJBContainerTransactionManager.destroyBeanAndRollback(EJBContainerTransactionManager.java:578)
	at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:701)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:519)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
	at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.messaging.jmq.jmsservice.JMSServiceException: rollbackTransaction: rollback transaction failed. Connection ID: 2346193787890764800, Transaction ID: 2346193788044086016, XID: (Available at FINE log level) Caused by:com.sun.messaging.jmq.jmsserver.util.BrokerException: Transaction XID mismatch 473032504C584E4E4F5732393233392C7365727665722C50383033372C00DE290000C3E3AAD1473032504C584E4E4F5732393233392C7365727665722C5038303337, expected 473032504C584E4E4F5732393233392C7365727665722C50383033372C01DD290000C3E3AAD1473032504C584E4E4F5732393233392C7365727665722C5038303337 for transaction 2346193788044086016
	at com.sun.messaging.jmq.jmsserver.service.imq.JMSServiceImpl.rollbackTransaction(JMSServiceImpl.java:1718)
	at com.sun.messaging.jms.ra.DirectXAResource.rollback(DirectXAResource.java:714)
	... 22 more
Caused by: com.sun.messaging.jmq.jmsserver.util.BrokerException: Transaction XID mismatch 473032504C584E4E4F5732393233392C7365727665722C50383033372C00DE290000C3E3AAD1473032504C584E4E4F5732393233392C7365727665722C5038303337, expected 473032504C584E4E4F5732393233392C7365727665722C50383033372C01DD290000C3E3AAD1473032504C584E4E4F5732393233392C7365727665722C5038303337 for transaction 2346193788044086016
	at com.sun.messaging.jmq.jmsserver.data.protocol.ProtocolImpl.rollbackTransaction(ProtocolImpl.java:921)
	at com.sun.messaging.jmq.jmsserver.service.imq.JMSServiceImpl.rollbackTransaction(JMSServiceImpl.java:1706)
	... 23 more
]]

[2017-03-15T12:51:02.058+0100] [glassfish 4.1] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=223 _ThreadName=__ejb-thread-pool6] [timeMillis: 1489578662058] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB TaskQueueServiceBean, method: public void org.oscm.taskhandling.bean.TaskQueueServiceBean.sendAllMessages(java.util.List)]]

[2017-03-15T12:51:02.059+0100] [glassfish 4.1] [WARNING] [] [javax.enterprise.ejb.container] [tid: _ThreadID=223 _ThreadName=__ejb-thread-pool6] [timeMillis: 1489578662059] [levelValue: 900] [[
  
javax.ejb.EJBException
	at com.sun.ejb.containers.EJBContainerTransactionManager.processSystemException(EJBContainerTransactionManager.java:752)
	at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:702)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:519)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
	at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.oscm.internal.types.exception.SaaSSystemException: EXCEPTIONID 1489578662040: javax.jms.JMSException: MQJMSRA_DS4001: JMSServiceException on send message:sendMessage: Sending message failed. Connection ID: 2346193787890764800 Caused by:com.sun.messaging.jmq.jmsserver.util.BrokerException: [B4403]: Exception on processing produced message PacketReference[1934-192.168.99.1(b4:41:42:5d:4c:9d)-1-1489578662032][TID=2346193788044086016, null]: Unexpected Broker Exception: [Transaction 2346193788044086016[COMPLETE(4)]: is not in STARTED(1) state] 
	at org.oscm.taskhandling.bean.TaskQueueServiceBean.sendObjectMessage(TaskQueueServiceBean.java:157)
	at org.oscm.taskhandling.bean.TaskQueueServiceBean.sendAllMessages(TaskQueueServiceBean.java:65)
	at sun.reflect.GeneratedMethodAccessor2395.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:101)
	... 4 more
Caused by: javax.jms.JMSException: MQJMSRA_DS4001: JMSServiceException on send message:sendMessage: Sending message failed. Connection ID: 2346193787890764800 Caused by:com.sun.messaging.jmq.jmsserver.util.BrokerException: [B4403]: Exception on processing produced message PacketReference[1934-192.168.99.1(b4:41:42:5d:4c:9d)-1-1489578662032][TID=2346193788044086016, null]: Unexpected Broker Exception: [Transaction 2346193788044086016[COMPLETE(4)]: is not in STARTED(1) state] 
	at com.sun.messaging.jms.ra.DirectSession._sendMessage(DirectSession.java:1995)
	at com.sun.messaging.jms.ra.DirectProducer._send(DirectProducer.java:1138)
	at com.sun.messaging.jms.ra.DirectProducer.send(DirectProducer.java:458)
	at org.oscm.taskhandling.bean.TaskQueueServiceBean.sendObjectMessage(TaskQueueServiceBean.java:151)
	... 33 more
Caused by: com.sun.messaging.jmq.jmsservice.JMSServiceException: sendMessage: Sending message failed. Connection ID: 2346193787890764800 Caused by:com.sun.messaging.jmq.jmsserver.util.BrokerException: [B4403]: Exception on processing produced message PacketReference[1934-192.168.99.1(b4:41:42:5d:4c:9d)-1-1489578662032][TID=2346193788044086016, null]: Unexpected Broker Exception: [Transaction 2346193788044086016[COMPLETE(4)]: is not in STARTED(1) state] 
	at com.sun.messaging.jmq.jmsserver.service.imq.JMSServiceImpl.sendMessage(JMSServiceImpl.java:1848)
	at com.sun.messaging.jms.ra.DirectSession._sendMessage(DirectSession.java:1990)
	... 36 more
Caused by: com.sun.messaging.jmq.jmsserver.util.BrokerException: [B4403]: Exception on processing produced message PacketReference[1934-192.168.99.1(b4:41:42:5d:4c:9d)-1-1489578662032][TID=2346193788044086016, null]: Unexpected Broker Exception: [Transaction 2346193788044086016[COMPLETE(4)]: is not in STARTED(1) state] 
	at com.sun.messaging.jmq.jmsserver.data.handlers.DataHandler.routeMessage(DataHandler.java:511)
	at com.sun.messaging.jmq.jmsserver.data.protocol.ProtocolImpl.processMessage(ProtocolImpl.java:1130)
	at com.sun.messaging.jmq.jmsserver.service.imq.JMSServiceImpl.sendMessage(JMSServiceImpl.java:1841)
	... 37 more
]]

**[Error msg in system.log]**
03/15/2017_12:51:02.041 FSP_INTS-BSS: ERROR: ThreadID __ejb-thread-pool6: TaskQueueServiceBean: 70054: Sending the process-related message to JMS queue failed
org.oscm.internal.types.exception.SaaSSystemException: EXCEPTIONID 1489578662040: javax.jms.JMSException: MQJMSRA_DS4001: JMSServiceException on send message:sendMessage: Sending message failed. Connection ID: 2346193787890764800 Caused by:com.sun.messaging.jmq.jmsserver.util.BrokerException: [B4403]: Exception on processing produced message PacketReference[1934-192.168.99.1(b4:41:42:5d:4c:9d)-1-1489578662032][TID=2346193788044086016, null]: Unexpected Broker Exception: [Transaction 2346193788044086016[COMPLETE(4)]: is not in STARTED(1) state] 
	at org.oscm.taskhandling.bean.TaskQueueServiceBean.sendObjectMessage(TaskQueueServiceBean.java:157)
	at org.oscm.taskhandling.bean.TaskQueueServiceBean.sendAllMessages(TaskQueueServiceBean.java:65)
	at sun.reflect.GeneratedMethodAccessor2395.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.jms.JMSException: MQJMSRA_DS4001: JMSServiceException on send message:sendMessage: Sending message failed. Connection ID: 2346193787890764800 Caused by:com.sun.messaging.jmq.jmsserver.util.BrokerException: [B4403]: Exception on processing produced message PacketReference[1934-192.168.99.1(b4:41:42:5d:4c:9d)-1-1489578662032][TID=2346193788044086016, null]: Unexpected Broker Exception: [Transaction 2346193788044086016[COMPLETE(4)]: is not in STARTED(1) state] 
	at com.sun.messaging.jms.ra.DirectSession._sendMessage(DirectSession.java:1995)
	at com.sun.messaging.jms.ra.DirectProducer._send(DirectProducer.java:1138)
	at com.sun.messaging.jms.ra.DirectProducer.send(DirectProducer.java:458)
	at org.oscm.taskhandling.bean.TaskQueueServiceBean.sendObjectMessage(TaskQueueServiceBean.java:151)
	... 33 more
Caused by: com.sun.messaging.jmq.jmsservice.JMSServiceException: sendMessage: Sending message failed. Connection ID: 2346193787890764800 Caused by:com.sun.messaging.jmq.jmsserver.util.BrokerException: [B4403]: Exception on processing produced message PacketReference[1934-192.168.99.1(b4:41:42:5d:4c:9d)-1-1489578662032][TID=2346193788044086016, null]: Unexpected Broker Exception: [Transaction 2346193788044086016[COMPLETE(4)]: is not in STARTED(1) state] 
	at com.sun.messaging.jmq.jmsserver.service.imq.JMSServiceImpl.sendMessage(JMSServiceImpl.java:1848)
	at com.sun.messaging.jms.ra.DirectSession._sendMessage(DirectSession.java:1990)
	... 36 more
Caused by: com.sun.messaging.jmq.jmsserver.util.BrokerException: [B4403]: Exception on processing produced message PacketReference[1934-192.168.99.1(b4:41:42:5d:4c:9d)-1-1489578662032][TID=2346193788044086016, null]: Unexpected Broker Exception: [Transaction 2346193788044086016[COMPLETE(4)]: is not in STARTED(1) state] 
	at com.sun.messaging.jmq.jmsserver.data.handlers.DataHandler.routeMessage(DataHandler.java:511)
	at com.sun.messaging.jmq.jmsserver.data.protocol.ProtocolImpl.processMessage(ProtocolImpl.java:1130)
	at com.sun.messaging.jmq.jmsserver.service.imq.JMSServiceImpl.sendMessage(JMSServiceImpl.java:1841)
	... 37 more
03/15/2017_12:51:02.042 FSP_INTS-BSS: ERROR: ThreadID __ejb-thread-pool6: TaskQueueServiceBean: 70248: There are 0 message(s) out of 1 is/are sent successfully: Sent Message #0 Failed ::Handler: org.oscm.taskhandling.operations.SendMailHandler, Payload: org.oscm.taskhandling.payloads.SendMailPayload, Details: ;

**Comment by StavrevaS** [comment]
@victorhrsilva how did you get this error? Automated tests or manual?

**Comment by victorhrsilva** [comment]
I get this error on the Automated performance tests, I am trying to track down it to see if I can reproduce it manually also.

**Comment by DawidCh** [comment]
May be related to #563 and should be fixed and tested together.

**Comment by GoebelL** [comment]
>May be related to #563 and should be fixed and tested together.
@DawidCh you have found a good solution on the JMS issue. Does this issue persist after the fix of #563?

**Comment by DawidCh** [comment]
@GoebelL No, the problem still persists.

**Comment by DawidCh** [comment]
The problem is still reproducible on few of our environments. It doesn’t have functional (user) impact (or we do not know it yet). All automated and manual tests we have performed doesn't indicate that there is problem with functionality.

**Comment by victorhrsilva** [comment]
[Version]
Glassfish4 - 1019 - 17.0.0

Issue still occurs on the automated tests with slide difference on the error message, but the stacktrace is the same. Please see attached an example:

**Comment by GoebelL** [comment]
This issue has been investigated deeply. Extensive analysis has shown that the initial JMS issues have been sucessfuly resolved by switching the message queue type to LOCAL for Glassfish server. There is no functional user impact after all. Currently there is no plan for handling the remaining log messages. Remaining to WONTFIX.
